[package]
name = "fumohouse_web"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["secrets"] }
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["tera"] }
rocket_sync_db_pools = { version = "0.1.0-rc.1", features = ["diesel_postgres_pool"] }

reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "1.4.8", features = ["postgres", "chrono"] }
chrono = "0.4.19"
dotenvy = "0.15.1"
argon2 = "0.4.0"
rand = { version = "0.8.5" }